//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.16 at 12:22:21 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.megapath.com/m360", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.matrix360.schema;
